### ISSUE TITLE
`install-scripts` error

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nupm#22]
Another error during `use nupm` is:

```Nushell
Error: nu::parser::extra_positional

  × Extra positional argument.
     ╭─[/home/kaathewise/fork/nupm/nupm/install.nu:105:1]
 105 │                 $package.scripts
 106 │                 | install-scripts $pkg_dir (script-dir --ensure) --force $force
     ·                                                                          ───┬──
     ·                                                                             ╰── extra positional argument
 107 │             }
     ╰────
  help: Usage: install-scripts {flags} <pkg_dir> <scripts_dir>
```

`install-scripts` uses the `--force(-f): bool`, which I think stopped taking arguments after one of the recent updates.

**Comment by KAAtheWiseGit** [comment]
Same for `install-path`.

**Comment by KAAtheWiseGit** [comment]
Ah, got it!  I use a cut release, not the one installed via Cargo, so I am behind the HEAD.

**Comment by amtoine** [comment]
> Ah, got it! I use a cut release, not the one installed via Cargo, so I am behind the HEAD.
>
yup makes sense :yum: 

we do not have a proper version system for Nupm right now, so you might want to lag behing the latest `HEAD` of `nushell/nupm` if you use the *stables* releases of Nushell :wink:
