### ISSUE TITLE
grab the nightly build of Nushell in the CI

### ISSUE THREAD

**Issue by amtoine** [nushell/nupm#29]
> An optimization might be to grab the latest nightly release binary instead of compiling, but that's a detail.

_Originally posted by @kubouch in https://github.com/nushell/nupm/issues/27#issuecomment-1758337811_

**Comment by amtoine** [comment]
my first experiment with this is to download the latest tarball with the GitHub API
```nushell
let latest = http get https://api.github.com/repos/nushell/nightly/releases
    | sort-by published_at --reverse | first

http get $latest.tarball_url | save --progress $"($latest.tag_name).tar.gz"
```

**Comment by kubouch** [comment]
Downloading nu-0.85.1-x86_64-linux-gnu-full.tar.gz from https://github.com/nushell/nightly/releases works for me. Not sure what a link to the latest would looks like, but I think it was possible to point at the latest release.

Using the api link above, you might want to use assets, not the tarball.

**Comment by fdncred** [comment]
Some quick fun hacking
```nushell
let dl = http get https://api.github.com/repos/nushell/nightly/releases | sort-by published_at --reverse | first
let assets = http get $dl.assets_url | select url name
# then pick the asset you want. I picked 19
let item = http get $assets.url.19
http get $item.browser_download_url | save -p $assets.name.19
```

**Comment by amtoine** [comment]
tweaked a bit what you told me and came up with
```nushell
def get-latest-nightly-build [target: string] {
    let latest = http get https://api.github.com/repos/nushell/nightly/releases
        | sort-by published_at --reverse | first

    let target = $latest.assets
        | select name browser_download_url
        | where name =~ $target
        | first

    http get $target.browser_download_url | save --progress --force $target.name
    print $"latest nightly build saved as '($target.name)'"
}
```
e.g. for my system
```nushell
get-latest-nightly-build x86_64-linux-gnu
```
followed by
```nushell
tar xvf nu-0.85.1-x86_64-linux-gnu-full.tar.gz --directory .
```

now let's translate that to the CI :ok_hand:
