### ISSUE TITLE
Install of nu-git-manager only works for me now when I explicitly list the entire path

### ISSUE THREAD

**Issue by stormasm** [nushell/nupm#44]
On a mac

I start out in this directory
```rust
~/j/tmp17/nu-git-manager> 
```

this works
```rust
nupm install --path ~/j/tmp17/nu-git-manager/
```

this works
```rust
nupm install --path /Users/ma/j/tmp17/nu-git-manager --force
```

this is broken
```rust
nupm install --path nu-git-manager --force

Error:   × Could not expand path
     ╭─[/Users/ma/.nupm/modules/nupm/install.nu:104:1]
 104 │ ] {
 105 │     let pkg_dir = $pkg_dir | path expand --strict
     ·                   ────┬───
     ·                       ╰── could not be expanded (path might not exist, non-final component is not a directory, or other cause)
 106 │ 
     ╰────

```

and I get the same error message if I do this
```rust
nupm install --path ./nu-git-manager --force
```

**Comment by stormasm** [comment]
Question ? Should this work ?

```rust
nupm install --path nu-git-manager --force
```

When I start out in this directory ?
```rust
~/j/tmp17/nu-git-manager> 
```

**Comment by amtoine** [comment]
if you're inside the `nu-git-manager` package already, then
```nushell
nupm install --path nu-git-manager --force
```
should not work because `./nu-git-manager/` does not contain a `package.nuon`

the error is here unhelpful and should be made clearer :+1:

**Comment by stormasm** [comment]
It seems to me that if I go to a directory that has a *package.nuon* file I should just be able to say

```rust
nupm install --force
```

and should find the package.nuon file in that directory and install it 😄

**Comment by amtoine** [comment]
we require the `--path` switch for now because we had in mind the possibility of a future *remote* install process, i.e. you could run `nupm install nu-git-manager` from anywhere, even without the source pulled down, and Nupm would still be able to install `nu-git-manager`.

`--path` would then force Nupm to use the local path instead of the *remote* registry of known packages :+1:

**Comment by stormasm** [comment]
```rust
nupm install --path nu-git-manager --force
```

I guess then this is my point --- the above command should just work when I go and type the above command when I am in the top level directory of the package

and currently it does not...

**Comment by stormasm** [comment]
Ok I understand now --- my bad...
I have to be one level up from where nu-git-manager is located.
Not actually inside the nu-git-manager directory...
That was my confusion 😄

**Comment by stormasm** [comment]
For my edification

This works when you are inside the nu-git-manager directory

```rust
nupm install --path .  --force
```

This works when you are one level up from the nu-git-manager directory

```rust
nupm install --path nu-git-manager --force
```

In summary

```rust
~/j/tmp17/nu-git-manager> cd ..
~/j/tmp17> nupm install --path nu-git-manager --force
2023-11-04T10:13:47.702|INF|installing package nu-git-manager
~/j/tmp17> cd nu-git-manager/
~/j/tmp17/nu-git-manager> nupm install --path .  --force
2023-11-04T10:15:55.925|INF|installing package nu-git-manager
~/j/tmp17/nu-git-manager> 
```

**Comment by amtoine** [comment]
> Ok I understand now --- my bad...
>
no worries :wink: 

> I have to be one level up from where nu-git-manager is located. Not actually inside the nu-git-manager directory... That was my confusion 😄
>
you can be anywhere you want, as long as you
- pass the `--path` switch to `nupm install`
- give the path to the directory where the `package.nuon` file is located
