### ISSUE TITLE
use nupm resets value of $env.NUPM_REGISTRIES

### ISSUE THREAD

**Issue by ddupas** [nushell/nupm#79]
## Description

i have 2 entries in my $env.NUPM_REGISTRIES , after use nupm there is only one

## Steps to reproduce

```nu
let fresh = { nupm: "https://raw.githubusercontent.com/nushell/nupm/main/registry.nuon",
nupm-porcelain: "https://raw.githubusercontent.com/ddupas/nupm-porcelain/main/registry.nuon"}
print $"config_local_nupm: [warn] set NUPM_REGISTRIES to ($fresh)"
$env.NUPM_REGISTRIES = $fresh 

use nupm

$env.NUPM_REGISTRIES
```

## Version

latest

**Comment by ddupas** [comment]
ignore

**Comment by ddupas** [comment]
i will look into it

**Comment by ddupas** [comment]
```nu
let fresh = {
		nupm_test: 'https://raw.githubusercontent.com/nushell/nupm/main/registry.nuon'
	}
	
	# check for $env.NUPM_REGISTRIES?	
	let nupm_r = $env.NUPM_REGISTRIES?

	if ( $nupm_r | is-empty ) {	
		print  $"nupm/mod.nu: [warn] set NUPM_REGISTRIES to ($fresh)"
		$env.NUPM_REGISTRIES = $fresh
	} else {

	# check if nupm_test is in list
	if ( $env.NUPM_REGISTRIES | get -i nupm_test | is-empty ) {
		print  $"nupm/mod.nu: [warn] adding ($fresh) to NUPM_REGISTRIES"
		$env.NUPM_REGISTRIES = ( 
			$env.NUPM_REGISTRIES
			| append $fresh
		)
	}

```

**Comment by ddupas** [comment]
i made a branch to submit a pr but i do not have permission

**Comment by ddupas** [comment]
plus i dont know how to use default so you can code this way better i am sure

**Comment by kubouch** [comment]
@ddupas `default` is super simple, it sets a default value if the input is null: `null | default 1` equals to 1. `2 | default 1` equals to 2. To open a PR, you need to fork this repository first, then push the branch to your fork. Then, you can open a PR against this repository via GitHub UI, or the Git CLI will even print a link to follow when you push something to your fork. I fixed this issue really quick now, but for the next time!
